# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_module', '0005_stock'),
        ('crm_module', '0003_auto_20170904_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_module.Contact')),
                ('produit', models.ManyToManyField(to='products_module.Produit')),
            ],
        ),
    ]
