# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
