# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut_client', models.CharField(choices=[('LEAD', 'Lead'), ('PROS', 'Prospect'), ('CLIE', 'CLIE')], default='PROS', max_length=4)),
                ('interraction', models.CharField(choices=[('PHYS', 'Contact Physique'), ('APPE', 'Appel Téléphonique'), ('MAIL', 'Email')], default='PHYS', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=250)),
                ('pays', models.CharField(max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_client', models.CharField(choices=[('FOUR', 'Fournisseur'), ('CLIE', 'Client')], default='CLIE', max_length=4)),
                ('statut_client', models.CharField(choices=[('LEAD', 'Lead'), ('PROS', 'Prospect'), ('CLIE', 'CLIE')], default='PROS', max_length=4)),
                ('interraction', models.CharField(choices=[('PHYS', 'Contact Physique'), ('APPE', 'Appel Téléphonique'), ('MAIL', 'Email')], default='MAIL', max_length=4)),
            ],
        ),
    ]
