# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='particulier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='statut_client',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('PROS', 'Prospect'), ('CLIE', 'Client')], default='PROS', max_length=4),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='statut_client',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('PROS', 'Prospect'), ('CLIE', 'Client')], default='PROS', max_length=4),
        ),
    ]
