# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_module', '0002_auto_20170904_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=10)),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('num_tva', models.CharField(blank=True, max_length=20)),
                ('type_client', models.CharField(choices=[('FOUR', 'Fournisseur'), ('CLIE', 'Client'), ('PART', 'Particulier')], default='CLIE', max_length=4)),
                ('statut_client', models.CharField(choices=[('LEAD', 'Lead'), ('PROS', 'Prospect'), ('CLIE', 'Client')], default='PROS', max_length=4)),
                ('interraction', models.CharField(choices=[('PHYS', 'Contact Physique'), ('APPE', 'Appel Téléphonique'), ('MAIL', 'Email')], default='MAIL', max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Particulier',
        ),
        migrations.DeleteModel(
            name='Professionnel',
        ),
    ]
