# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('origin', models.CharField(max_length=50)),
                ('ean', models.CharField(blank=True, max_length=13)),
                ('package_number', models.CharField(blank=True, max_length=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
