# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('origine', models.CharField(max_length=50)),
                ('ean', models.CharField(max_length=13)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_revente_gros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_revente_particuliers', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
