# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0002_auto_20170818_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='numero_lot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
