# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0004_auto_20170820_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products_module.Produit')),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
